#!/sbin/sh

console=$(cat /tmp/console)
[ "$console" ] || console=/proc/$$/fd/1

print() {
	if [ "$1" ]; then
		echo "ui_print - $1" > "$console"
	else
		echo "ui_print  " > "$console"
	fi
	echo
}

abort() {
	[ "$1" ] && {
		print "Error: $1!"
		print "Aborting..."
	}
	exit 1
}

temp=/tmp/anykernel/
MAGISKBIN=/temp/anykernel/tools/

print "Disabling avb-verity in the fstab..."

if [ -f $temp/dtb ]; then
{
	print "Found dtbo image: dtb"
	$MAGISKBIN/magiskboot --dtb-patch $temp/dtb
	print "Script finished"
}
else
{
	print "Unable to find the dtb!" && print ""
}
fi

exit 0
